### ISSUE TITLE
Pages not rendering properly

### ISSUE THREAD

**Issue by bogdan-mainwp** [lukecarbis/mainwp#1]
Screenshot:
![bug](https://cloud.githubusercontent.com/assets/6987660/10817716/0370b152-7e3c-11e5-9822-b03fb1bf7fc9.png)

How do duplicate:
Go to the MainWP > Posts page:
Search for Posts on on some child site
(here you will get good table)
Next go some other page
Return to the MainWP > Posts > Manage page
(here you will be able to see the issue)

This issue is present on following pages: MainWP Posts, MainWP Pages, MainWP Themes, MainWP Plugins, MainWP Users.

Thanks

**Comment by lukecarbis** [comment]
Resolved in https://github.com/lukecarbis/mainwp/commit/85c6cc466f19402272ce3b2e641d7d2450032997
